# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.12
    command: mongod --port 27018
    restart: always
    ports:
      - 27018:27018
    environment:
      TZ: Europe/Rome
      MONGO_INITDB_DATABASE: stelapodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - myMongoDb2:/data/db
      - myMongoConfig2:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27018/

volumes:
  myMongoDb2:
  myMongoConfig2: